package com.csnt.ins.model.hjpt;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("cardupload", "csntID", Cardupload.class);
		arp.addMapping("obuupload", "csntID", Obuupload.class);
		arp.addMapping("vehicleupload", "csntID", Vehicleupload.class);
	}
}

