package com.csnt.ins.model.hjpt;

import com.csnt.ins.model.hjpt.base.BaseCardupload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cardupload extends BaseCardupload<Cardupload> {
	public static final Cardupload dao = new Cardupload().dao();
}
