package com.csnt.ins.model.hjpt;

import com.csnt.ins.model.hjpt.base.BaseObuupload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Obuupload extends BaseObuupload<Obuupload> {
	public static final Obuupload dao = new Obuupload().dao();
}
