package com.csnt.ins.model.hjpt;

import com.csnt.ins.model.hjpt.base.BaseVehicleupload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Vehicleupload extends BaseVehicleupload<Vehicleupload> {
	public static final Vehicleupload dao = new Vehicleupload().dao();
}
