package com.csnt.ins.model.issuer;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
//		// Composite Primary Key order: id,opTime
//		arp.addMapping("etc_cardinfo_history", "id,opTime", EtcCardinfoHistory.class);
//		// Composite Primary Key order: id,opTime
//		arp.addMapping("etc_obuinfo_history", "id,opTime", EtcObuinfoHistory.class);
//		// Composite Primary Key order: id,opTime
//		arp.addMapping("etc_userinfo_history", "id,opTime", EtcUserinfoHistory.class);
//		// Composite Primary Key order: id,opTime
//		arp.addMapping("etc_vehicleinfo_history", "id,opTime", EtcVehicleinfoHistory.class);

		//系统用户表
		arp.addMapping("pos_user", "UUID", PosUser.class);
		//用户登录日志表
		arp.addMapping("pos_login_log", "UUID", PosLoginLog.class);
		//在线订单表
		arp.addMapping("online_orders", "orderId", OnlineOrders.class);

		//发行记录表
		arp.addMapping("etc_issued_record", "uuid", EtcIssuedRecord.class);
		//线下渠道用户信息表
		arp.addMapping("etc_ofl_userinfo", "userId", EtcOflUserinfo.class);
		//线下渠道车辆信息表
		arp.addMapping("etc_ofl_vehicleinfo", "vehicleId", EtcOflVehicleinfo.class);
	}
}

