package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BaseEtcCardinfoHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EtcCardinfoHistory extends BaseEtcCardinfoHistory<EtcCardinfoHistory> {
	public static final EtcCardinfoHistory dao = new EtcCardinfoHistory().dao();
}
