package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BaseEtcIssuedRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EtcIssuedRecord extends BaseEtcIssuedRecord<EtcIssuedRecord> {
	public static final EtcIssuedRecord dao = new EtcIssuedRecord().dao();
}
