package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BaseEtcOflVehicleinfo;
import com.csnt.ins.utils.DbUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EtcOflVehicleinfo extends BaseEtcOflVehicleinfo<EtcOflVehicleinfo> {
    public static final EtcOflVehicleinfo dao = new EtcOflVehicleinfo().dao();

    /**
     * 根据vehicleId查询未在线下渠道注册的车辆
     *
     * @param vehicleId
     * @return
     */
    public static EtcOflVehicleinfo findFirstRegeistedOflVehicleByVehicleId(String vehicleId) {
        return dao.findFirst(DbUtil.getSql("queryRegistedEtcOflVehicleByVehicleId"), vehicleId);
    }
}
