package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BaseEtcObuinfoHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EtcObuinfoHistory extends BaseEtcObuinfoHistory<EtcObuinfoHistory> {
	public static final EtcObuinfoHistory dao = new EtcObuinfoHistory().dao();
}
