package com.csnt.ins.model.issuer;


import com.csnt.ins.model.issuer.base.BaseEtcUserinfoHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EtcUserinfoHistory extends BaseEtcUserinfoHistory<EtcUserinfoHistory> {
	public static final EtcUserinfoHistory dao = new EtcUserinfoHistory().dao();
}
