package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BaseEtcVehicleinfoHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EtcVehicleinfoHistory extends BaseEtcVehicleinfoHistory<EtcVehicleinfoHistory> {
	public static final EtcVehicleinfoHistory dao = new EtcVehicleinfoHistory().dao();
}
