package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BaseImCardReleaseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImCardReleaseInfo extends BaseImCardReleaseInfo<ImCardReleaseInfo> {
	public static final ImCardReleaseInfo dao = new ImCardReleaseInfo().dao();
}
