package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BaseImObuReleaseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImObuReleaseInfo extends BaseImObuReleaseInfo<ImObuReleaseInfo> {
	public static final ImObuReleaseInfo dao = new ImObuReleaseInfo().dao();
}
