package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BaseOnlineOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OnlineOrders extends BaseOnlineOrders<OnlineOrders> {
	public static final OnlineOrders dao = new OnlineOrders().dao();

}
