package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BasePosLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PosLoginLog extends BasePosLoginLog<PosLoginLog> {
	public static final PosLoginLog dao = new PosLoginLog().dao();
}
