package com.csnt.ins.model.issuer;

import com.csnt.ins.model.issuer.base.BasePosUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PosUser extends BasePosUser<PosUser> {
	public static final PosUser dao = new PosUser().dao();
}
