package com.csnt.ins.model.hjpt.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCardupload<M extends BaseCardupload<M>> extends Model<M> implements IBean {

	public void setCsntID(java.lang.String csntID) {
		set("csntID", csntID);
	}
	
	public java.lang.String getCsntID() {
		return getStr("csntID");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setCardType(java.lang.Integer cardType) {
		set("cardType", cardType);
	}
	
	public java.lang.Integer getCardType() {
		return getInt("cardType");
	}

	public void setBrand(java.lang.Integer brand) {
		set("brand", brand);
	}
	
	public java.lang.Integer getBrand() {
		return getInt("brand");
	}

	public void setModel(java.lang.String model) {
		set("model", model);
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public void setAgencyId(java.lang.String agencyId) {
		set("agencyId", agencyId);
	}
	
	public java.lang.String getAgencyId() {
		return getStr("agencyId");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public void setVehicleId(java.lang.String vehicleId) {
		set("vehicleId", vehicleId);
	}
	
	public java.lang.String getVehicleId() {
		return getStr("vehicleId");
	}

	public void setEnableTime(java.lang.String enableTime) {
		set("enableTime", enableTime);
	}
	
	public java.lang.String getEnableTime() {
		return getStr("enableTime");
	}

	public void setExpireTime(java.lang.String expireTime) {
		set("expireTime", expireTime);
	}
	
	public java.lang.String getExpireTime() {
		return getStr("expireTime");
	}

	public void setIssuedType(java.lang.Integer issuedType) {
		set("issuedType", issuedType);
	}
	
	public java.lang.Integer getIssuedType() {
		return getInt("issuedType");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channelId", channelId);
	}
	
	public java.lang.String getChannelId() {
		return getStr("channelId");
	}

	public void setIssuedTime(java.lang.String issuedTime) {
		set("issuedTime", issuedTime);
	}
	
	public java.lang.String getIssuedTime() {
		return getStr("issuedTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setStatusChangeTime(java.lang.String statusChangeTime) {
		set("statusChangeTime", statusChangeTime);
	}
	
	public java.lang.String getStatusChangeTime() {
		return getStr("statusChangeTime");
	}

	public void setOperation(java.lang.Integer operation) {
		set("operation", operation);
	}
	
	public java.lang.Integer getOperation() {
		return getInt("operation");
	}

	public void setCsntCreateTime(java.util.Date csntCreateTime) {
		set("csntCreateTime", csntCreateTime);
	}
	
	public java.util.Date getCsntCreateTime() {
		return get("csntCreateTime");
	}

	public void setCsntfileName(java.lang.String csntfileName) {
		set("csntfileName", csntfileName);
	}
	
	public java.lang.String getCsntfileName() {
		return getStr("csntfileName");
	}

	public void setBackup(java.lang.String backup) {
		set("backup", backup);
	}
	
	public java.lang.String getBackup() {
		return getStr("backup");
	}

	public void setIssucess(java.lang.String issucess) {
		set("issucess", issucess);
	}
	
	public java.lang.String getIssucess() {
		return getStr("issucess");
	}

}
