package com.csnt.ins.model.hjpt.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVehicleupload<M extends BaseVehicleupload<M>> extends Model<M> implements IBean {

	public void setCsntID(java.lang.String csntID) {
		set("csntID", csntID);
	}
	
	public java.lang.String getCsntID() {
		return getStr("csntID");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public void setOwnerName(java.lang.String ownerName) {
		set("ownerName", ownerName);
	}
	
	public java.lang.String getOwnerName() {
		return getStr("ownerName");
	}

	public void setOwnerIdType(java.lang.Integer ownerIdType) {
		set("ownerIdType", ownerIdType);
	}
	
	public java.lang.Integer getOwnerIdType() {
		return getInt("ownerIdType");
	}

	public void setOwnerIdNum(java.lang.String ownerIdNum) {
		set("ownerIdNum", ownerIdNum);
	}
	
	public java.lang.String getOwnerIdNum() {
		return getStr("ownerIdNum");
	}

	public void setOwnerTel(java.lang.String ownerTel) {
		set("ownerTel", ownerTel);
	}
	
	public java.lang.String getOwnerTel() {
		return getStr("ownerTel");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}
	
	public java.lang.String getContact() {
		return getStr("contact");
	}

	public void setRegisteredType(java.lang.Integer registeredType) {
		set("registeredType", registeredType);
	}
	
	public java.lang.Integer getRegisteredType() {
		return getInt("registeredType");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channelId", channelId);
	}
	
	public java.lang.String getChannelId() {
		return getStr("channelId");
	}

	public void setRegisteredTime(java.lang.String registeredTime) {
		set("registeredTime", registeredTime);
	}
	
	public java.lang.String getRegisteredTime() {
		return getStr("registeredTime");
	}

	public void setVehicleType(java.lang.String vehicleType) {
		set("vehicleType", vehicleType);
	}
	
	public java.lang.String getVehicleType() {
		return getStr("vehicleType");
	}

	public void setVehicleModel(java.lang.String vehicleModel) {
		set("vehicleModel", vehicleModel);
	}
	
	public java.lang.String getVehicleModel() {
		return getStr("vehicleModel");
	}

	public void setUseCharacter(java.lang.Integer useCharacter) {
		set("useCharacter", useCharacter);
	}
	
	public java.lang.Integer getUseCharacter() {
		return getInt("useCharacter");
	}

	public void setVin(java.lang.String vin) {
		set("vin", vin);
	}
	
	public java.lang.String getVin() {
		return getStr("vin");
	}

	public void setEngineNum(java.lang.String engineNum) {
		set("engineNum", engineNum);
	}
	
	public java.lang.String getEngineNum() {
		return getStr("engineNum");
	}

	public void setRegisterDate(java.lang.String registerDate) {
		set("registerDate", registerDate);
	}
	
	public java.lang.String getRegisterDate() {
		return getStr("registerDate");
	}

	public void setIssueDate(java.lang.String issueDate) {
		set("issueDate", issueDate);
	}
	
	public java.lang.String getIssueDate() {
		return getStr("issueDate");
	}

	public void setFileNum(java.lang.String fileNum) {
		set("fileNum", fileNum);
	}
	
	public java.lang.String getFileNum() {
		return getStr("fileNum");
	}

	public void setApprovedCount(java.lang.Integer approvedCount) {
		set("approvedCount", approvedCount);
	}
	
	public java.lang.Integer getApprovedCount() {
		return getInt("approvedCount");
	}

	public void setTotalMass(java.lang.Integer totalMass) {
		set("totalMass", totalMass);
	}
	
	public java.lang.Integer getTotalMass() {
		return getInt("totalMass");
	}

	public void setMaintenanceMass(java.lang.Integer maintenanceMass) {
		set("maintenanceMass", maintenanceMass);
	}
	
	public java.lang.Integer getMaintenanceMass() {
		return getInt("maintenanceMass");
	}

	public void setPermittedWeight(java.lang.Integer permittedWeight) {
		set("permittedWeight", permittedWeight);
	}
	
	public java.lang.Integer getPermittedWeight() {
		return getInt("permittedWeight");
	}

	public void setOutsideDimensions(java.lang.String outsideDimensions) {
		set("outsideDimensions", outsideDimensions);
	}
	
	public java.lang.String getOutsideDimensions() {
		return getStr("outsideDimensions");
	}

	public void setPermittedTowWeight(java.lang.Integer permittedTowWeight) {
		set("permittedTowWeight", permittedTowWeight);
	}
	
	public java.lang.Integer getPermittedTowWeight() {
		return getInt("permittedTowWeight");
	}

	public void setTestRecord(java.lang.String testRecord) {
		set("testRecord", testRecord);
	}
	
	public java.lang.String getTestRecord() {
		return getStr("testRecord");
	}

	public void setWheelCount(java.lang.Integer wheelCount) {
		set("wheelCount", wheelCount);
	}
	
	public java.lang.Integer getWheelCount() {
		return getInt("wheelCount");
	}

	public void setAxleCount(java.lang.Integer axleCount) {
		set("axleCount", axleCount);
	}
	
	public java.lang.Integer getAxleCount() {
		return getInt("axleCount");
	}

	public void setAxleDistance(java.lang.Integer axleDistance) {
		set("axleDistance", axleDistance);
	}
	
	public java.lang.Integer getAxleDistance() {
		return getInt("axleDistance");
	}

	public void setAxisType(java.lang.String axisType) {
		set("axisType", axisType);
	}
	
	public java.lang.String getAxisType() {
		return getStr("axisType");
	}

	public void setOperation(java.lang.Integer operation) {
		set("operation", operation);
	}
	
	public java.lang.Integer getOperation() {
		return getInt("operation");
	}

	public void setCsntCreateTime(java.util.Date csntCreateTime) {
		set("csntCreateTime", csntCreateTime);
	}
	
	public java.util.Date getCsntCreateTime() {
		return get("csntCreateTime");
	}

	public void setCsntfileName(java.lang.String csntfileName) {
		set("csntfileName", csntfileName);
	}
	
	public java.lang.String getCsntfileName() {
		return getStr("csntfileName");
	}

	public void setBackup(java.lang.String backup) {
		set("backup", backup);
	}
	
	public java.lang.String getBackup() {
		return getStr("backup");
	}

	public void setIssucess(java.lang.String issucess) {
		set("issucess", issucess);
	}
	
	public java.lang.String getIssucess() {
		return getStr("issucess");
	}

}
