package com.csnt.ins.model.yg.base;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public abstract class BaseTblUsercard<M extends BaseTblUsercard<M>> extends Model<M> implements IBean {

	//region  部中心字段
	public void setId(java.lang.String id) {
		set("ID", id);
	}
	
	public java.lang.String getId() {
		return getStr("ID");
	}

	public void setCardType(Integer cardtype) {
		set("CARDTYPE", cardtype);
	}
	
	public Integer getCardType() {
		return get("CARDTYPE");
	}

	public void setBrand(Integer brand) {
		set("BRAND", brand);
	}
	
	public Integer getBrand() {
		return get("BRAND");
	}

	public void setModel(java.lang.String model) {
		set("MODEL", model);
	}
	
	public java.lang.String getModel() {
		return getStr("MODEL");
	}

	public void setAgencyId(java.lang.String agencyid) {
		set("AGENCYID", agencyid);
	}
	
	public java.lang.String getAgencyId() {
		return getStr("AGENCYID");
	}

	public void setUserId(java.lang.String userid) {
		set("USERID", userid);
	}
	
	public java.lang.String getUserId() {
		return getStr("USERID");
	}

	public void setVehicleId(java.lang.String vehicleid) {
		set("VEHICLEID", vehicleid);
	}
	
	public java.lang.String getVehicleId() {
		return getStr("VEHICLEID");
	}

	public void setEnableTime(java.util.Date enabletime) {
		set("ENABLETIME", enabletime);
	}
	
	public java.util.Date getEnableTime() {
		return get("ENABLETIME");
	}

	public void setExpireTime(java.util.Date expiretime) {
		set("EXPIRETIME", expiretime);
	}
	
	public java.util.Date getExpireTime() {
		return get("EXPIRETIME");
	}

	public void setIssuedType(Integer issuedtype) {
		set("ISSUEDTYPE", issuedtype);
	}
	
	public Integer getIssuedType() {
		return get("ISSUEDTYPE");
	}

	public void setChannelId(java.lang.String channelid) {
		set("CHANNELID", channelid);
	}
	
	public java.lang.String getChannelId() {
		return getStr("CHANNELID");
	}

	public void setIssuedTime(java.util.Date issuedtime) {
		set("ISSUEDTIME", issuedtime);
	}
	
	public java.util.Date getIssuedTime() {
		return get("ISSUEDTIME");
	}

	public void setStatus(Integer status) {
		set("STATUS", status);
	}
	
	public Integer getStatus() {
		return get("STATUS");
	}

	public void setStatusChangeTime(java.util.Date statuschangetime) {
		set("STATUSCHANGETIME", statuschangetime);
	}
	
	public java.util.Date getStatusChangeTime() {
		return get("STATUSCHANGETIME");
	}

	@JsonProperty("operation")
	public void setFlag(Integer flag) {
		set("FLAG", flag);
	}

	@JsonProperty("operation")
	public Integer getFlag() {
		return get("FLAG");
	}
	//endregion

	//region  自定义字段
	@JsonIgnore
	public void setUploadFlag(Integer uploadflag) {
		set("UPLOADFLAG", uploadflag);
	}
	@JsonIgnore
	public Integer getUploadFlag() {
		return get("UPLOADFLAG");
	}
	@JsonIgnore
	public void setUploadtime(java.util.Date uploadtime) {
		set("UPLOADTIME", uploadtime);
	}
	@JsonIgnore
	public java.util.Date getUploadtime() {
		return get("UPLOADTIME");
	}
	@JsonIgnore
	public void setSpare1(Integer spare1) {
		set("SPARE1", spare1);
	}
	@JsonIgnore
	public Integer getSpare1() {
		return get("SPARE1");
	}
	@JsonIgnore
	public void setSpare2(Integer spare2) {
		set("SPARE2", spare2);
	}
	@JsonIgnore
	public Integer getSpare2() {
		return get("SPARE2");
	}
	@JsonIgnore
	public void setSpare3(java.lang.String spare3) {
		set("SPARE3", spare3);
	}
	@JsonIgnore
	public java.lang.String getSpare3() {
		return getStr("SPARE3");
	}
	@JsonIgnore
	public void setSpare4(java.lang.String spare4) {
		set("SPARE4", spare4);
	}
	@JsonIgnore
	public java.lang.String getSpare4() {
		return getStr("SPARE4");
	}
	//endregion
}
