package com.csnt.ins.model.yg.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTblVehicle<M extends BaseTblVehicle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}
	
	public java.lang.String getId() {
		return getStr("ID");
	}

	public void setType(java.math.BigDecimal type) {
		set("TYPE", type);
	}
	
	public java.math.BigDecimal getType() {
		return get("TYPE");
	}

	public void setUserid(java.lang.String userid) {
		set("USERID", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("USERID");
	}

	public void setOwnername(java.lang.String ownername) {
		set("OWNERNAME", ownername);
	}
	
	public java.lang.String getOwnername() {
		return getStr("OWNERNAME");
	}

	public void setOwneridtype(java.math.BigDecimal owneridtype) {
		set("OWNERIDTYPE", owneridtype);
	}
	
	public java.math.BigDecimal getOwneridtype() {
		return get("OWNERIDTYPE");
	}

	public void setOwneridnum(java.lang.String owneridnum) {
		set("OWNERIDNUM", owneridnum);
	}
	
	public java.lang.String getOwneridnum() {
		return getStr("OWNERIDNUM");
	}

	public void setRegisteredtype(java.math.BigDecimal registeredtype) {
		set("REGISTEREDTYPE", registeredtype);
	}
	
	public java.math.BigDecimal getRegisteredtype() {
		return get("REGISTEREDTYPE");
	}

	public void setChannelid(java.lang.String channelid) {
		set("CHANNELID", channelid);
	}
	
	public java.lang.String getChannelid() {
		return getStr("CHANNELID");
	}

	public void setRegisteredtime(java.util.Date registeredtime) {
		set("REGISTEREDTIME", registeredtime);
	}
	
	public java.util.Date getRegisteredtime() {
		return get("REGISTEREDTIME");
	}

	public void setOwnertel(java.lang.String ownertel) {
		set("OWNERTEL", ownertel);
	}
	
	public java.lang.String getOwnertel() {
		return getStr("OWNERTEL");
	}

	public void setAddress(java.lang.String address) {
		set("ADDRESS", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("ADDRESS");
	}

	public void setContact(java.lang.String contact) {
		set("CONTACT", contact);
	}
	
	public java.lang.String getContact() {
		return getStr("CONTACT");
	}

	public void setVehicletype(java.lang.String vehicletype) {
		set("VEHICLETYPE", vehicletype);
	}
	
	public java.lang.String getVehicletype() {
		return getStr("VEHICLETYPE");
	}

	public void setVehiclemodel(java.lang.String vehiclemodel) {
		set("VEHICLEMODEL", vehiclemodel);
	}
	
	public java.lang.String getVehiclemodel() {
		return getStr("VEHICLEMODEL");
	}

	public void setUsecharacter(java.math.BigDecimal usecharacter) {
		set("USECHARACTER", usecharacter);
	}
	
	public java.math.BigDecimal getUsecharacter() {
		return get("USECHARACTER");
	}

	public void setVin(java.lang.String vin) {
		set("VIN", vin);
	}
	
	public java.lang.String getVin() {
		return getStr("VIN");
	}

	public void setEnginenum(java.lang.String enginenum) {
		set("ENGINENUM", enginenum);
	}
	
	public java.lang.String getEnginenum() {
		return getStr("ENGINENUM");
	}

	public void setRegisterdate(java.lang.String registerdate) {
		set("REGISTERDATE", registerdate);
	}
	
	public java.lang.String getRegisterdate() {
		return getStr("REGISTERDATE");
	}

	public void setIssuedate(java.lang.String issuedate) {
		set("ISSUEDATE", issuedate);
	}
	
	public java.lang.String getIssuedate() {
		return getStr("ISSUEDATE");
	}

	public void setFilenum(java.lang.String filenum) {
		set("FILENUM", filenum);
	}
	
	public java.lang.String getFilenum() {
		return getStr("FILENUM");
	}

	public void setApprovedcount(java.math.BigDecimal approvedcount) {
		set("APPROVEDCOUNT", approvedcount);
	}
	
	public java.math.BigDecimal getApprovedcount() {
		return get("APPROVEDCOUNT");
	}

	public void setTotalmass(java.lang.String totalmass) {
		set("TOTALMASS", totalmass);
	}
	
	public java.lang.String getTotalmass() {
		return getStr("TOTALMASS");
	}

	public void setMaintenancemass(java.lang.String maintenancemass) {
		set("MAINTENANCEMASS", maintenancemass);
	}
	
	public java.lang.String getMaintenancemass() {
		return getStr("MAINTENANCEMASS");
	}

	public void setPermittedweight(java.lang.String permittedweight) {
		set("PERMITTEDWEIGHT", permittedweight);
	}
	
	public java.lang.String getPermittedweight() {
		return getStr("PERMITTEDWEIGHT");
	}

	public void setOutsidedimensions(java.lang.String outsidedimensions) {
		set("OUTSIDEDIMENSIONS", outsidedimensions);
	}
	
	public java.lang.String getOutsidedimensions() {
		return getStr("OUTSIDEDIMENSIONS");
	}

	public void setPermittedtowweight(java.lang.String permittedtowweight) {
		set("PERMITTEDTOWWEIGHT", permittedtowweight);
	}
	
	public java.lang.String getPermittedtowweight() {
		return getStr("PERMITTEDTOWWEIGHT");
	}

	public void setTestrecord(java.lang.String testrecord) {
		set("TESTRECORD", testrecord);
	}
	
	public java.lang.String getTestrecord() {
		return getStr("TESTRECORD");
	}

	public void setWheelcount(java.math.BigDecimal wheelcount) {
		set("WHEELCOUNT", wheelcount);
	}
	
	public java.math.BigDecimal getWheelcount() {
		return get("WHEELCOUNT");
	}

	public void setAxlecount(java.math.BigDecimal axlecount) {
		set("AXLECOUNT", axlecount);
	}
	
	public java.math.BigDecimal getAxlecount() {
		return get("AXLECOUNT");
	}

	public void setAxledistance(java.lang.String axledistance) {
		set("AXLEDISTANCE", axledistance);
	}
	
	public java.lang.String getAxledistance() {
		return getStr("AXLEDISTANCE");
	}

	public void setAxistype(java.lang.String axistype) {
		set("AXISTYPE", axistype);
	}
	
	public java.lang.String getAxistype() {
		return getStr("AXISTYPE");
	}

	public void setUploadflag(java.math.BigDecimal uploadflag) {
		set("UPLOADFLAG", uploadflag);
	}
	
	public java.math.BigDecimal getUploadflag() {
		return get("UPLOADFLAG");
	}

	public void setFlag(java.math.BigDecimal flag) {
		set("FLAG", flag);
	}
	
	public java.math.BigDecimal getFlag() {
		return get("FLAG");
	}

	public void setUploadtime(java.util.Date uploadtime) {
		set("UPLOADTIME", uploadtime);
	}
	
	public java.util.Date getUploadtime() {
		return get("UPLOADTIME");
	}

	public void setSpare1(java.math.BigDecimal spare1) {
		set("SPARE1", spare1);
	}
	
	public java.math.BigDecimal getSpare1() {
		return get("SPARE1");
	}

	public void setSpare2(java.math.BigDecimal spare2) {
		set("SPARE2", spare2);
	}
	
	public java.math.BigDecimal getSpare2() {
		return get("SPARE2");
	}

	public void setSpare3(java.lang.String spare3) {
		set("SPARE3", spare3);
	}
	
	public java.lang.String getSpare3() {
		return getStr("SPARE3");
	}

	public void setSpare4(java.lang.String spare4) {
		set("SPARE4", spare4);
	}
	
	public java.lang.String getSpare4() {
		return getStr("SPARE4");
	}

}
