package com.csnt.ins.model.json;

import com.csnt.ins.utils.MathUtil;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class EtcObuinfoJson<M extends EtcObuinfoJson<M>> extends Model<M> implements IBean {

    //region  部中心字段
    public void setId(String id) {
        put("id", id);
    }

    public String getId() {
        return getStr("id");
    }

    public void setBrand(Integer brand) {
        put("brand", brand);
    }

    public Integer getBrand() {
        return MathUtil.asInteger(get("brand"));
    }

    public void setModel(String model) {
        put("model", model);
    }

    public String getModel() {
        return getStr("model");
    }

    public void setObuSign(Integer obuSign) {
        put("obuSign", obuSign);
    }

    public Integer getObuSign() {
        return MathUtil.asInteger(get("obuSign"));
    }

    public void setUserId(String userId) {
        put("userId", userId);
    }

    public String getUserId() {
        return getStr("userId");
    }

    public void setVehicleId(String vehicleId) {
        put("vehicleId", vehicleId);
    }

    public String getVehicleId() {
        return getStr("vehicleId");
    }

    public void setEnableTime(String enableTime) {
        put("enableTime", enableTime);
    }

    public String getEnableTime() {
        return get("enableTime");
    }

    public void setExpireTime(String expireTime) {
        put("expireTime", expireTime);
    }

    public String getExpireTime() {
        return getStr("expireTime").split("T")[0];
    }

    public void setRegisteredType(Integer registeredType) {
        put("registeredType", registeredType);
    }

    public Integer getRegisteredType() {
        return getInt("registeredType");
    }

    public void setRegisteredChannelId(String registeredChannelId) {
        put("registeredChannelId", registeredChannelId);
    }

    public String getRegisteredChannelId() {
        return getStr("registeredChannelId");
    }

    public void setRegisteredTime(String registeredTime) {
        put("registeredTime", registeredTime);
    }

    public String getRegisteredTime() {
        return get("registeredTime");
    }

    public void setInstallType(Integer installType) {
        put("installType", installType);
    }

    public Integer getInstallType() {
        return getInt("installType");
    }

    public void setInstallChannelId(String installChannelId) {
        put("installChannelId", installChannelId);
    }

    public String getInstallChannelId() {
        return getStr("installChannelId");
    }

    public void setInstallTime(String installTime) {
        put("installTime", installTime);
    }

    public String getInstallTime() {
        return get("installTime");
    }

    public void setStatus(Integer status) {
        put("status", status);
    }

    public Integer getStatus() {
        return getInt("status");
    }

    public void setStatusChangeTime(String statusChangeTime) {
        put("statusChangeTime", statusChangeTime);
    }

    public String getStatusChangeTime() {
        return get("statusChangeTime");
    }

    public void setOperation(Integer operation) {
        put("operation", operation);
    }

    public Integer getOperation() {
        return getInt("operation");
    }
    //endregion

//    //region  自定义字段
//    @JsonIgnore
//    public void setChannelType(String channelType) {
//        put("channelType", channelType);
//    }
//
//    @JsonIgnore
//    public String getChannelType() {
//        return getStr("channelType");
//    }
//
//    @JsonIgnore
//    public void setOrgId(String orgId) {
//        put("orgId", orgId);
//    }
//
//    @JsonIgnore
//    public String getOrgId() {
//        return getStr("orgId");
//    }
//
//    @JsonIgnore
//    public void setOperatorId(String operatorId) {
//        put("operatorId", operatorId);
//    }
//
//    @JsonIgnore
//    public String getOperatorId() {
//        return getStr("operatorId");
//    }
//
//    @JsonIgnore
//    public void setOpTime(String opTime) {
//        put("opTime", opTime);
//    }
//
//    @JsonIgnore
//    public String getOpTime() {
//        return get("opTime");
//    }
//
//    @JsonIgnore
//    public void setUploadResult(String uploadResult) {
//        put("uploadResult", uploadResult);
//    }
//
//    @JsonIgnore
//    public String getUploadResult() {
//        return getStr("uploadResult");
//    }
//
//    @JsonIgnore
//    public void setUploadResultMsg(String uploadResultMsg) {
//        put("uploadResultMsg", uploadResultMsg);
//    }
//
//    @JsonIgnore
//    public String getUploadResultMsg() {
//        return getStr("uploadResultMsg");
//    }
//
//    @JsonIgnore
//    public void setUploadTime(String uploadTime) {
//        put("uploadTime", uploadTime);
//    }
//
//    @JsonIgnore
//    public String getUploadTime() {
//        return get("uploadTime");
//    }
//
//    @JsonIgnore
//    public void setResponseTime(String responseTime) {
//        put("responseTime", responseTime);
//    }
//
//    @JsonIgnore
//    public String getResponseTime() {
//        return get("responseTime");
//    }
//
//    @JsonIgnore
//    public void setIsuploadBank(Integer isuploadBank) {
//        put("isuploadBank", isuploadBank);
//    }
//
//    @JsonIgnore
//    public Integer getIsuploadBank() {
//        return getInt("isuploadBank");
//    }
//
//    @JsonIgnore
//    public void setUploadBankResult(String uploadBankResult) {
//        put("uploadBankResult", uploadBankResult);
//    }
//
//    @JsonIgnore
//    public String getUploadBankResult() {
//        return getStr("uploadBankResult");
//    }
//
//    @JsonIgnore
//    public void setUploadBankResultMsg(String uploadBankResultMsg) {
//        put("uploadBankResultMsg", uploadBankResultMsg);
//    }
//
//    @JsonIgnore
//    public String getUploadBankResultMsg() {
//        return getStr("uploadBankResultMsg");
//    }
//
//    @JsonIgnore
//    public void setUploadBankTime(Integer uploadBankTime) {
//        put("uploadBankTime", uploadBankTime);
//    }
//
//    @JsonIgnore
//    public Integer getUploadBankTime() {
//        return getInt("uploadBankTime");
//    }
//
//    @JsonIgnore
//    public void setUploadStatus(Integer uploadStatus) {
//        put("uploadStatus", uploadStatus);
//    }
//
//    @JsonIgnore
//    public Integer getUploadStatus() {
//        return getInt("uploadStatus");
//    }
//
//    @JsonIgnore
//    public void setCreateTime(String createTime) {
//        put("createTime", createTime);
//    }
//
//    @JsonIgnore
//    public String getCreateTime() {
//        return get("createTime");
//    }
//
//    @JsonIgnore
//    public void setUpStringTime(String upStringTime) {
//        put("upStringTime", upStringTime);
//    }
//
//    @JsonIgnore
//    public String getUpStringTime() {
//        return get("upStringTime");
//    }
//
//    @JsonIgnore
//    public void setBackup1(Integer backup1) {
//        put("backup1", backup1);
//    }
//
//    @JsonIgnore
//    public Integer getBackup1() {
//        return getInt("backup1");
//    }
//
//    @JsonIgnore
//    public void setBackup2(Integer backup2) {
//        put("backup2", backup2);
//    }
//
//    @JsonIgnore
//    public Integer getBackup2() {
//        return getInt("backup2");
//    }
//
//    @JsonIgnore
//    public void setBackup3(Integer backup3) {
//        put("backup3", backup3);
//    }
//
//    @JsonIgnore
//    public Integer getBackup3() {
//        return getInt("backup3");
//    }
//
//    @JsonIgnore
//    public void setBackup4(String backup4) {
//        put("backup4", backup4);
//    }
//
//    @JsonIgnore
//    public String getBackup4() {
//        return getStr("backup4");
//    }
//
//    @JsonIgnore
//    public void setBackup5(String backup5) {
//        put("backup5", backup5);
//    }
//
//    @JsonIgnore
//    public String getBackup5() {
//        return getStr("backup5");
//    }
//    //endregion
}
