package com.csnt.ins.model.json;


import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class EtcUserinfoJson<M extends EtcUserinfoJson<M>> extends Model<M> implements IBean {

    //region  部中心字段
    public void setId(String id) {
        set("id", id);
    }

    public String getId() {
        return getStr("id");
    }

    public void setUserType(Integer userType) {
        set("userType", userType);
    }

    public Integer getUserType() {
        return getInt("userType");
    }

    public void setUserName(String userName) {
        set("userName", userName);
    }

    public String getUserName() {
        return getStr("userName");
    }

    public void setUserIdType(Integer userIdType) {
        set("userIdType", userIdType);
    }

    public Integer getUserIdType() {
        return getInt("userIdType");
    }

    public void setUserIdNum(String userIdNum) {
        set("userIdNum", userIdNum);
    }

    public String getUserIdNum() {
        return getStr("userIdNum");
    }

    public void setTel(String tel) {
        set("tel", tel);
    }

    public String getTel() {
        return getStr("tel");
    }

    public void setAddress(String address) {
        set("address", address);
    }

    public String getAddress() {
        return getStr("address");
    }

    public void setRegisteredType(Integer registeredType) {
        set("registeredType", registeredType);
    }

    public Integer getRegisteredType() {
        return getInt("registeredType");
    }

    public void setChannelId(String channelId) {
        set("channelId", channelId);
    }

    public String getChannelId() {
        return getStr("channelId");
    }

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "GMT+8")
    public void setRegisteredTime(Date registeredTime) {
        set("registeredTime", registeredTime);
    }

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "GMT+8")
    public Date getRegisteredTime() {
        return get("registeredTime");
    }

    public void setDepartment(String department) {
        set("department", department);
    }

    public String getDepartment() {
        return getStr("department");
    }

    public void setAgentName(String agentName) {
        set("agentName", agentName);
    }

    public String getAgentName() {
        return getStr("agentName");
    }

    public void setAgentIdType(Integer agentIdType) {
        set("agentIdType", agentIdType);
    }

    public Integer getAgentIdType() {
        return getInt("agentIdType");
    }

    public void setAgentIdNum(String agentIdNum) {
        set("agentIdNum", agentIdNum);
    }

    public String getAgentIdNum() {
        return getStr("agentIdNum");
    }

    public void setStatus(Integer status) {
        set("status", status);
    }

    public Integer getStatus() {
        return getInt("status");
    }

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "GMT+8")
    public void setStatusChangeTime(Date statusChangeTime) {
        set("statusChangeTime", statusChangeTime);
    }

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "GMT+8")
    public Date getStatusChangeTime() {
        return get("statusChangeTime");
    }

    public void setOperation(Integer operation) {
        set("operation", operation);
    }

    public Integer getOperation() {
        return getInt("operation");
    }
    //endregion


//    //region  自定义字段
//    @JsonIgnore
//    public void setBank(String bank) {
//        set("bank", bank);
//    }
//
//    @JsonIgnore
//    public String getBank() {
//        return getStr("bank");
//    }
//
//    @JsonIgnore
//    public void setBankAddr(String bankAddr) {
//        set("bankAddr", bankAddr);
//    }
//
//    @JsonIgnore
//    public String getBankAddr() {
//        return getStr("bankAddr");
//    }
//
//    @JsonIgnore
//    public void setBankAccount(String bankAccount) {
//        set("bankAccount", bankAccount);
//    }
//
//    @JsonIgnore
//    public String getBankAccount() {
//        return getStr("bankAccount");
//    }
//
//    @JsonIgnore
//    public void setTaxpayerCode(String taxpayerCode) {
//        set("taxpayerCode", taxpayerCode);
//    }
//
//    @JsonIgnore
//    public String getTaxpayerCode() {
//        return getStr("taxpayerCode");
//    }
//
//    @JsonIgnore
//    public void setFaceFeatureVersion(String faceFeatureVersion) {
//        set("faceFeatureVersion", faceFeatureVersion);
//    }
//
//    @JsonIgnore
//    public String getFaceFeatureVersion() {
//        return getStr("faceFeatureVersion");
//    }
//
//    @JsonIgnore
//    public void setFaceFeatureCode(String faceFeatureCode) {
//        set("faceFeatureCode", faceFeatureCode);
//    }
//
//    @JsonIgnore
//    public String getFaceFeatureCode() {
//        return getStr("faceFeatureCode");
//    }
//
//    @JsonIgnore
//    public void setChannelType(String channelType) {
//        set("channelType", channelType);
//    }
//
//    @JsonIgnore
//    public String getChannelType() {
//        return getStr("channelType");
//    }
//
//    @JsonIgnore
//    public void setNeedupload(Integer needupload) {
//        set("needupload", needupload);
//    }
//
//    @JsonIgnore
//    public Integer getNeedupload() {
//        return getInt("needupload");
//    }
//
//    @JsonIgnore
//    public void setOrgId(String orgId) {
//        set("orgId", orgId);
//    }
//
//    @JsonIgnore
//    public String getOrgId() {
//        return getStr("orgId");
//    }
//
//    @JsonIgnore
//    public void setOperatorId(String operatorId) {
//        set("operatorId", operatorId);
//    }
//
//    @JsonIgnore
//    public String getOperatorId() {
//        return getStr("operatorId");
//    }
//
//    @JsonIgnore
//    public void setOpTime(Date opTime) {
//        set("opTime", opTime);
//    }
//
//    @JsonIgnore
//    public Date getOpTime() {
//        return get("opTime");
//    }
//
//    @JsonIgnore
//    public void setUploadResult(String uploadResult) {
//        set("uploadResult", uploadResult);
//    }
//
//    @JsonIgnore
//    public String getUploadResult() {
//        return getStr("uploadResult");
//    }
//
//    @JsonIgnore
//    public void setUploadResultMsg(String uploadResultMsg) {
//        set("uploadResultMsg", uploadResultMsg);
//    }
//
//    @JsonIgnore
//    public String getUploadResultMsg() {
//        return getStr("uploadResultMsg");
//    }
//
//    @JsonIgnore
//    public void setUploadTime(Date uploadTime) {
//        set("uploadTime", uploadTime);
//    }
//
//    @JsonIgnore
//    public Date getUploadTime() {
//        return get("uploadTime");
//    }
//
//    @JsonIgnore
//    public void setResponseTime(Date responseTime) {
//        set("responseTime", responseTime);
//    }
//
//    @JsonIgnore
//    public Date getResponseTime() {
//        return get("responseTime");
//    }
//
//    @JsonIgnore
//    public void setIsuploadBank(Integer isuploadBank) {
//        set("isuploadBank", isuploadBank);
//    }
//
//    @JsonIgnore
//    public Integer getIsuploadBank() {
//        return getInt("isuploadBank");
//    }
//
//    @JsonIgnore
//    public void setUploadBankResult(String uploadBankResult) {
//        set("uploadBankResult", uploadBankResult);
//    }
//
//    @JsonIgnore
//    public String getUploadBankResult() {
//        return getStr("uploadBankResult");
//    }
//
//    @JsonIgnore
//    public void setUploadBankResultMsg(String uploadBankResultMsg) {
//        set("uploadBankResultMsg", uploadBankResultMsg);
//    }
//
//    @JsonIgnore
//    public String getUploadBankResultMsg() {
//        return getStr("uploadBankResultMsg");
//    }
//
//    @JsonIgnore
//    public void setUploadBankTime(Date uploadBankTime) {
//        set("uploadBankTime", uploadBankTime);
//    }
//
//    @JsonIgnore
//    public Date getUploadBankTime() {
//        return get("uploadBankTime");
//    }
//
//    @JsonIgnore
//    public void setUploadStatus(Integer uploadStatus) {
//        set("uploadStatus", uploadStatus);
//    }
//
//    @JsonIgnore
//    public Integer getUploadStatus() {
//        return getInt("uploadStatus");
//    }
//
//    @JsonIgnore
//    public void setCreateTime(Date createTime) {
//        set("createTime", createTime);
//    }
//
//    @JsonIgnore
//    public Date getCreateTime() {
//        return get("createTime");
//    }
//
//    @JsonIgnore
//    public void setUpdateTime(Date updateTime) {
//        set("updateTime", updateTime);
//    }
//
//    @JsonIgnore
//    public Date getUpdateTime() {
//        return get("updateTime");
//    }
//
//    @JsonIgnore
//    public void setBackup1(Integer backup1) {
//        set("backup1", backup1);
//    }
//
//    @JsonIgnore
//    public Integer getBackup1() {
//        return getInt("backup1");
//    }
//
//    @JsonIgnore
//    public void setBackup2(Integer backup2) {
//        set("backup2", backup2);
//    }
//
//    @JsonIgnore
//    public Integer getBackup2() {
//        return getInt("backup2");
//    }
//
//    @JsonIgnore
//    public void setBackup3(Integer backup3) {
//        set("backup3", backup3);
//    }
//
//    @JsonIgnore
//    public Integer getBackup3() {
//        return getInt("backup3");
//    }
//
//    @JsonIgnore
//    public void setBackup4(String backup4) {
//        set("backup4", backup4);
//    }
//
//    @JsonIgnore
//    public String getBackup4() {
//        return getStr("backup4");
//    }
//
//    @JsonIgnore
//    public void setBackup5(String backup5) {
//        set("backup5", backup5);
//    }
//
//    @JsonIgnore
//    public String getBackup5() {
//        return getStr("backup5");
//    }
//    //endregion
}
