package com.csnt.ins.model.json;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class EtcVehicleinfoJson<M extends EtcVehicleinfoJson<M>> extends Model<M> implements IBean {

    //region  部中心字段
    public void setId(String id) {
        set("id", id);
    }

    public String getId() {
        return getStr("id");
    }

    public void setType(Integer type) {
        set("type", type);
    }

    public Integer getType() {
        return getInt("type");
    }

    public void setUserId(String userId) {
        set("userId", userId);
    }

    public String getUserId() {
        return getStr("userId");
    }

    public void setOwnerName(String ownerName) {
        set("ownerName", ownerName);
    }

    public String getOwnerName() {
        return getStr("ownerName");
    }

    public void setOwnerIdType(Integer ownerIdType) {
        set("ownerIdType", ownerIdType);
    }

    public Integer getOwnerIdType() {
        return getInt("ownerIdType");
    }

    public void setOwnerIdNum(String ownerIdNum) {
        set("ownerIdNum", ownerIdNum);
    }

    public String getOwnerIdNum() {
        return getStr("ownerIdNum");
    }

    public void setOwnerTel(String ownerTel) {
        set("ownerTel", ownerTel);
    }

    public String getOwnerTel() {
        return getStr("ownerTel");
    }

    public void setAddress(String address) {
        set("address", address);
    }

    public String getAddress() {
        return getStr("address");
    }

    public void setContact(String contact) {
        set("contact", contact);
    }

    public String getContact() {
        return getStr("contact");
    }

    public void setRegisteredType(Integer registeredType) {
        set("registeredType", registeredType);
    }

    public Integer getRegisteredType() {
        return getInt("registeredType");
    }

    public void setChannelId(String channelId) {
        set("channelId", channelId);
    }

    public String getChannelId() {
        return getStr("channelId");
    }

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "GMT+8")
    public void setRegisteredTime(Date registeredTime) {
        set("registeredTime", registeredTime);
    }

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "GMT+8")
    public Date getRegisteredTime() {
        return get("registeredTime");
    }

    public void setVehicleType(String vehicleType) {
        set("vehicleType", vehicleType);
    }

    public String getVehicleType() {
        return getStr("vehicleType");
    }

    public void setVehicleModel(String vehicleModel) {
        set("vehicleModel", vehicleModel);
    }

    public String getVehicleModel() {
        return getStr("vehicleModel");
    }

    public void setUseCharacter(Integer useCharacter) {
        set("useCharacter", useCharacter);
    }

    public Integer getUseCharacter() {
        return getInt("useCharacter");
    }

    @JsonProperty("VIN")
    public void setVin(String vin) {
        set("VIN", vin);
    }

    @JsonProperty("VIN")
    public String getVin() {
        return getStr("VIN");
    }

    public void setEngineNum(String engineNum) {
        set("engineNum", engineNum);
    }

    public String getEngineNum() {
        return getStr("engineNum");
    }

    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    public void setRegisterDate(Date registerDate) {
        set("registerDate", registerDate);
    }

    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    public Date getRegisterDate() {
        return get("registerDate");
    }

    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    public void setIssueDate(Date issueDate) {
        set("issueDate", issueDate);
    }

    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    public Date getIssueDate() {
        return get("issueDate");
    }

    public void setFileNum(String fileNum) {
        set("fileNum", fileNum);
    }

    public String getFileNum() {
        return getStr("fileNum");
    }

    public void setApprovedCount(Integer approvedCount) {
        set("approvedCount", approvedCount);
    }

    public Integer getApprovedCount() {
        return getInt("approvedCount");
    }

    public void setTotalMass(Integer totalMass) {
        set("totalMass", totalMass);
    }

    public Integer getTotalMass() {
        return getInt("totalMass");
    }

    public void setMaintenanceMass(Integer maintenanceMass) {
        set("maintenanceMass", maintenanceMass);
    }

    public Integer getMaintenanceMass() {
        return getInt("maintenanceMass");
    }

    public void setPermittedWeight(Integer permittedWeight) {
        set("permittedWeight", permittedWeight);
    }

    public Integer getPermittedWeight() {
        return getInt("permittedWeight");
    }

    public void setOutsideDimensions(String outsideDimensions) {
        set("outsideDimensions", outsideDimensions);
    }

    public String getOutsideDimensions() {
        return getStr("outsideDimensions");
    }

    public void setPermittedTowWeight(Integer permittedTowWeight) {
        set("permittedTowWeight", permittedTowWeight);
    }

    public Integer getPermittedTowWeight() {
        return getInt("permittedTowWeight");
    }

    public void setTestRecord(String testRecord) {
        set("testRecord", testRecord);
    }

    public String getTestRecord() {
        return getStr("testRecord");
    }

    public void setWheelCount(Integer wheelCount) {
        set("wheelCount", wheelCount);
    }

    public Integer getWheelCount() {
        return getInt("wheelCount");
    }

    public void setAxleCount(Integer axleCount) {
        set("axleCount", axleCount);
    }

    public Integer getAxleCount() {
        return getInt("axleCount");
    }

    public void setAxleDistance(Integer axleDistance) {
        set("axleDistance", axleDistance);
    }

    public Integer getAxleDistance() {
        return getInt("axleDistance");
    }

    public void setAxisType(String axisType) {
        set("axisType", axisType);
    }

    public String getAxisType() {
        return getStr("axisType");
    }

    public void setOperation(Integer operation) {
        set("operation", operation);
    }

    public Integer getOperation() {
        return getInt("operation");
    }
    //endregion

//    //region  自定义字段
//    @JsonIgnore
//    public void setVehicleFeatureVersion(String vehicleFeatureVersion) {
//        set("vehicleFeatureVersion", vehicleFeatureVersion);
//    }
//
//    @JsonIgnore
//    public String getVehicleFeatureVersion() {
//        return getStr("vehicleFeatureVersion");
//    }
//
//    @JsonIgnore
//    public void setVehicleFeatureCode(String vehicleFeatureCode) {
//        set("vehicleFeatureCode", vehicleFeatureCode);
//    }
//
//    @JsonIgnore
//    public String getVehicleFeatureCode() {
//        return getStr("vehicleFeatureCode");
//    }
//
//    @JsonIgnore
//    public void setPayAccountNum(String payAccountNum) {
//        set("payAccountNum", payAccountNum);
//    }
//
//    @JsonIgnore
//    public String getPayAccountNum() {
//        return getStr("payAccountNum");
//    }
//
//    @JsonIgnore
//    public void setChannelType(String channelType) {
//        set("channelType", channelType);
//    }
//
//    @JsonIgnore
//    public String getChannelType() {
//        return getStr("channelType");
//    }
//
//    @JsonIgnore
//    public void setOrgId(String orgId) {
//        set("orgId", orgId);
//    }
//
//    @JsonIgnore
//    public String getOrgId() {
//        return getStr("orgId");
//    }
//
//    @JsonIgnore
//    public void setOperatorId(String operatorId) {
//        set("operatorId", operatorId);
//    }
//
//    @JsonIgnore
//    public String getOperatorId() {
//        return getStr("operatorId");
//    }
//
//    @JsonIgnore
//    public void setOpTime(Date opTime) {
//        set("opTime", opTime);
//    }
//
//    @JsonIgnore
//    public Date getOpTime() {
//        return get("opTime");
//    }
//
//    @JsonIgnore
//    public void setUploadResult(String uploadResult) {
//        set("uploadResult", uploadResult);
//    }
//
//    @JsonIgnore
//    public String getUploadResult() {
//        return getStr("uploadResult");
//    }
//
//    @JsonIgnore
//    public void setUploadResultMsg(String uploadResultMsg) {
//        set("uploadResultMsg", uploadResultMsg);
//    }
//
//    @JsonIgnore
//    public String getUploadResultMsg() {
//        return getStr("uploadResultMsg");
//    }
//
//    @JsonIgnore
//    public void setUploadTime(Date uploadTime) {
//        set("uploadTime", uploadTime);
//    }
//
//    @JsonIgnore
//    public Date getUploadTime() {
//        return get("uploadTime");
//    }
//
//    @JsonIgnore
//    public void setResponseTime(Date responseTime) {
//        set("responseTime", responseTime);
//    }
//
//    @JsonIgnore
//    public Date getResponseTime() {
//        return get("responseTime");
//    }
//
//    @JsonIgnore
//    public void setIsuploadBank(Integer isuploadBank) {
//        set("isuploadBank", isuploadBank);
//    }
//
//    @JsonIgnore
//    public Integer getIsuploadBank() {
//        return getInt("isuploadBank");
//    }
//
//    @JsonIgnore
//    public void setUploadBankResult(String uploadBankResult) {
//        set("uploadBankResult", uploadBankResult);
//    }
//
//    @JsonIgnore
//    public String getUploadBankResult() {
//        return getStr("uploadBankResult");
//    }
//
//    @JsonIgnore
//    public void setUploadBankResultMsg(String uploadBankResultMsg) {
//        set("uploadBankResultMsg", uploadBankResultMsg);
//    }
//
//    @JsonIgnore
//    public String getUploadBankResultMsg() {
//        return getStr("uploadBankResultMsg");
//    }
//
//    @JsonIgnore
//    public void setUploadBankTime(Date uploadBankTime) {
//        set("uploadBankTime", uploadBankTime);
//    }
//
//    @JsonIgnore
//    public Date getUploadBankTime() {
//        return get("uploadBankTime");
//    }
//
//    @JsonIgnore
//    public void setUploadStatus(Integer uploadStatus) {
//        set("uploadStatus", uploadStatus);
//    }
//
//    @JsonIgnore
//    public Integer getUploadStatus() {
//        return getInt("uploadStatus");
//    }
//
//    @JsonIgnore
//    public void setCreateTime(Date createTime) {
//        set("createTime", createTime);
//    }
//
//    @JsonIgnore
//    public Date getCreateTime() {
//        return get("createTime");
//    }
//
//    @JsonIgnore
//    public void setUpdateTime(Date updateTime) {
//        set("updateTime", updateTime);
//    }
//
//    @JsonIgnore
//    public Date getUpdateTime() {
//        return get("updateTime");
//    }
//
//    @JsonIgnore
//    public void setBackup1(Integer backup1) {
//        set("backup1", backup1);
//    }
//
//    @JsonIgnore
//    public Integer getBackup1() {
//        return getInt("backup1");
//    }
//
//    @JsonIgnore
//    public void setBackup2(Integer backup2) {
//        set("backup2", backup2);
//    }
//
//    @JsonIgnore
//    public Integer getBackup2() {
//        return getInt("backup2");
//    }
//
//    @JsonIgnore
//    public void setBackup3(Integer backup3) {
//        set("backup3", backup3);
//    }
//
//    @JsonIgnore
//    public Integer getBackup3() {
//        return getInt("backup3");
//    }
//
//    @JsonIgnore
//    public void setBackup4(String backup4) {
//        set("backup4", backup4);
//    }
//
//    @JsonIgnore
//    public String getBackup4() {
//        return getStr("backup4");
//    }
//
//    @JsonIgnore
//    public void setBackup5(String backup5) {
//        set("backup5", backup5);
//    }
//
//    @JsonIgnore
//    public String getBackup5() {
//        return getStr("backup5");
//    }
//    //endregion
}
