package com.csnt.ins.model.issuer.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEtcCardinfoHistory<M extends BaseEtcCardinfoHistory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setCardType(java.lang.Integer cardType) {
		set("cardType", cardType);
	}
	
	public java.lang.Integer getCardType() {
		return getInt("cardType");
	}

	public void setBrand(java.lang.Integer brand) {
		set("brand", brand);
	}
	
	public java.lang.Integer getBrand() {
		return getInt("brand");
	}

	public void setModel(java.lang.String model) {
		set("model", model);
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public void setAgencyId(java.lang.String agencyId) {
		set("agencyId", agencyId);
	}
	
	public java.lang.String getAgencyId() {
		return getStr("agencyId");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public void setVehicleId(java.lang.String vehicleId) {
		set("vehicleId", vehicleId);
	}
	
	public java.lang.String getVehicleId() {
		return getStr("vehicleId");
	}

	public void setEnableTime(java.util.Date enableTime) {
		set("enableTime", enableTime);
	}
	
	public java.util.Date getEnableTime() {
		return get("enableTime");
	}

	public void setExpireTime(java.util.Date expireTime) {
		set("expireTime", expireTime);
	}
	
	public java.util.Date getExpireTime() {
		return get("expireTime");
	}

	public void setIssuedType(java.lang.Integer issuedType) {
		set("issuedType", issuedType);
	}
	
	public java.lang.Integer getIssuedType() {
		return getInt("issuedType");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channelId", channelId);
	}
	
	public java.lang.String getChannelId() {
		return getStr("channelId");
	}

	public void setIssuedTime(java.util.Date issuedTime) {
		set("issuedTime", issuedTime);
	}
	
	public java.util.Date getIssuedTime() {
		return get("issuedTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setStatusChangeTime(java.util.Date statusChangeTime) {
		set("statusChangeTime", statusChangeTime);
	}
	
	public java.util.Date getStatusChangeTime() {
		return get("statusChangeTime");
	}

	public void setOperation(java.lang.Integer operation) {
		set("operation", operation);
	}
	
	public java.lang.Integer getOperation() {
		return getInt("operation");
	}

	public void setAccountid(java.lang.String accountid) {
		set("accountid", accountid);
	}
	
	public java.lang.String getAccountid() {
		return getStr("accountid");
	}

	public void setLinkmobile(java.lang.String linkmobile) {
		set("linkmobile", linkmobile);
	}
	
	public java.lang.String getLinkmobile() {
		return getStr("linkmobile");
	}

	public void setBankusername(java.lang.String bankusername) {
		set("bankusername", bankusername);
	}
	
	public java.lang.String getBankusername() {
		return getStr("bankusername");
	}

	public void setCertsn(java.lang.String certsn) {
		set("certsn", certsn);
	}
	
	public java.lang.String getCertsn() {
		return getStr("certsn");
	}

	public void setPosid(java.lang.String posid) {
		set("posid", posid);
	}
	
	public java.lang.String getPosid() {
		return getStr("posid");
	}

	public void setGentime(java.lang.String gentime) {
		set("gentime", gentime);
	}
	
	public java.lang.String getGentime() {
		return getStr("gentime");
	}

	public void setTrxSerno(java.lang.String trxSerno) {
		set("trx_serno", trxSerno);
	}
	
	public java.lang.String getTrxSerno() {
		return getStr("trx_serno");
	}

	public void setEmployeeid(java.lang.String employeeid) {
		set("employeeid", employeeid);
	}
	
	public java.lang.String getEmployeeid() {
		return getStr("employeeid");
	}

	public void setOrgTrxSerno(java.lang.String orgTrxSerno) {
		set("org_trx_serno", orgTrxSerno);
	}
	
	public java.lang.String getOrgTrxSerno() {
		return getStr("org_trx_serno");
	}

	public void setAccType(java.lang.Integer accType) {
		set("acc_type", accType);
	}
	
	public java.lang.Integer getAccType() {
		return getInt("acc_type");
	}

	public void setBankPost(java.lang.String bankPost) {
		set("bankPost", bankPost);
	}
	
	public java.lang.String getBankPost() {
		return getStr("bankPost");
	}

	public void setChannelType(java.lang.String channelType) {
		set("channelType", channelType);
	}
	
	public java.lang.String getChannelType() {
		return getStr("channelType");
	}

	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}
	
	public java.lang.String getOrgId() {
		return getStr("orgId");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}
	
	public java.lang.String getOperatorId() {
		return getStr("operatorId");
	}

	public void setOpTime(java.util.Date opTime) {
		set("opTime", opTime);
	}
	
	public java.util.Date getOpTime() {
		return get("opTime");
	}

	public void setUploadResult(java.lang.String uploadResult) {
		set("uploadResult", uploadResult);
	}
	
	public java.lang.String getUploadResult() {
		return getStr("uploadResult");
	}

	public void setUploadResultMsg(java.lang.String uploadResultMsg) {
		set("uploadResultMsg", uploadResultMsg);
	}
	
	public java.lang.String getUploadResultMsg() {
		return getStr("uploadResultMsg");
	}

	public void setUploadTime(java.util.Date uploadTime) {
		set("uploadTime", uploadTime);
	}
	
	public java.util.Date getUploadTime() {
		return get("uploadTime");
	}

	public void setResponseTime(java.util.Date responseTime) {
		set("responseTime", responseTime);
	}
	
	public java.util.Date getResponseTime() {
		return get("responseTime");
	}

	public void setIsuploadBank(java.lang.Integer isuploadBank) {
		set("isuploadBank", isuploadBank);
	}
	
	public java.lang.Integer getIsuploadBank() {
		return getInt("isuploadBank");
	}

	public void setUploadBankResult(java.lang.String uploadBankResult) {
		set("uploadBankResult", uploadBankResult);
	}
	
	public java.lang.String getUploadBankResult() {
		return getStr("uploadBankResult");
	}

	public void setUploadBankResultMsg(java.lang.String uploadBankResultMsg) {
		set("uploadBankResultMsg", uploadBankResultMsg);
	}
	
	public java.lang.String getUploadBankResultMsg() {
		return getStr("uploadBankResultMsg");
	}

	public void setUploadBankTime(java.lang.Integer uploadBankTime) {
		set("uploadBankTime", uploadBankTime);
	}
	
	public java.lang.Integer getUploadBankTime() {
		return getInt("uploadBankTime");
	}

	public void setUploadStatus(java.lang.Integer uploadStatus) {
		set("uploadStatus", uploadStatus);
	}
	
	public java.lang.Integer getUploadStatus() {
		return getInt("uploadStatus");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setBackup1(java.lang.Integer backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.Integer getBackup1() {
		return getInt("backup1");
	}

	public void setBackup2(java.lang.Integer backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.Integer getBackup2() {
		return getInt("backup2");
	}

	public void setBackup3(java.lang.Integer backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.Integer getBackup3() {
		return getInt("backup3");
	}

	public void setBackup4(java.lang.String backup4) {
		set("backup4", backup4);
	}
	
	public java.lang.String getBackup4() {
		return getStr("backup4");
	}

	public void setBackup5(java.lang.String backup5) {
		set("backup5", backup5);
	}
	
	public java.lang.String getBackup5() {
		return getStr("backup5");
	}

}
