package com.csnt.ins.model.issuer.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEtcObuinfoHistory<M extends BaseEtcObuinfoHistory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setBrand(java.lang.Integer brand) {
		set("brand", brand);
	}
	
	public java.lang.Integer getBrand() {
		return getInt("brand");
	}

	public void setModel(java.lang.String model) {
		set("model", model);
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public void setObuSign(java.lang.Integer obuSign) {
		set("obuSign", obuSign);
	}
	
	public java.lang.Integer getObuSign() {
		return getInt("obuSign");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public void setVehicleId(java.lang.String vehicleId) {
		set("vehicleId", vehicleId);
	}
	
	public java.lang.String getVehicleId() {
		return getStr("vehicleId");
	}

	public void setEnableTime(java.util.Date enableTime) {
		set("enableTime", enableTime);
	}
	
	public java.util.Date getEnableTime() {
		return get("enableTime");
	}

	public void setExpireTime(java.util.Date expireTime) {
		set("expireTime", expireTime);
	}
	
	public java.util.Date getExpireTime() {
		return get("expireTime");
	}

	public void setRegisteredType(java.lang.Integer registeredType) {
		set("registeredType", registeredType);
	}
	
	public java.lang.Integer getRegisteredType() {
		return getInt("registeredType");
	}

	public void setRegisteredChannelId(java.lang.String registeredChannelId) {
		set("registeredChannelId", registeredChannelId);
	}
	
	public java.lang.String getRegisteredChannelId() {
		return getStr("registeredChannelId");
	}

	public void setRegisteredTime(java.util.Date registeredTime) {
		set("registeredTime", registeredTime);
	}
	
	public java.util.Date getRegisteredTime() {
		return get("registeredTime");
	}

	public void setInstallType(java.lang.Integer installType) {
		set("installType", installType);
	}
	
	public java.lang.Integer getInstallType() {
		return getInt("installType");
	}

	public void setInstallChannelId(java.lang.String installChannelId) {
		set("installChannelId", installChannelId);
	}
	
	public java.lang.String getInstallChannelId() {
		return getStr("installChannelId");
	}

	public void setInstallTime(java.util.Date installTime) {
		set("installTime", installTime);
	}
	
	public java.util.Date getInstallTime() {
		return get("installTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setStatusChangeTime(java.util.Date statusChangeTime) {
		set("statusChangeTime", statusChangeTime);
	}
	
	public java.util.Date getStatusChangeTime() {
		return get("statusChangeTime");
	}

	public void setOperation(java.lang.Integer operation) {
		set("operation", operation);
	}
	
	public java.lang.Integer getOperation() {
		return getInt("operation");
	}

	public void setChannelType(java.lang.String channelType) {
		set("channelType", channelType);
	}
	
	public java.lang.String getChannelType() {
		return getStr("channelType");
	}

	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}
	
	public java.lang.String getOrgId() {
		return getStr("orgId");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}
	
	public java.lang.String getOperatorId() {
		return getStr("operatorId");
	}

	public void setOpTime(java.util.Date opTime) {
		set("opTime", opTime);
	}
	
	public java.util.Date getOpTime() {
		return get("opTime");
	}

	public void setUploadResult(java.lang.String uploadResult) {
		set("uploadResult", uploadResult);
	}
	
	public java.lang.String getUploadResult() {
		return getStr("uploadResult");
	}

	public void setUploadResultMsg(java.lang.String uploadResultMsg) {
		set("uploadResultMsg", uploadResultMsg);
	}
	
	public java.lang.String getUploadResultMsg() {
		return getStr("uploadResultMsg");
	}

	public void setUploadTime(java.util.Date uploadTime) {
		set("uploadTime", uploadTime);
	}
	
	public java.util.Date getUploadTime() {
		return get("uploadTime");
	}

	public void setResponseTime(java.util.Date responseTime) {
		set("responseTime", responseTime);
	}
	
	public java.util.Date getResponseTime() {
		return get("responseTime");
	}

	public void setIsuploadBank(java.lang.Integer isuploadBank) {
		set("isuploadBank", isuploadBank);
	}
	
	public java.lang.Integer getIsuploadBank() {
		return getInt("isuploadBank");
	}

	public void setUploadBankResult(java.lang.String uploadBankResult) {
		set("uploadBankResult", uploadBankResult);
	}
	
	public java.lang.String getUploadBankResult() {
		return getStr("uploadBankResult");
	}

	public void setUploadBankResultMsg(java.lang.String uploadBankResultMsg) {
		set("uploadBankResultMsg", uploadBankResultMsg);
	}
	
	public java.lang.String getUploadBankResultMsg() {
		return getStr("uploadBankResultMsg");
	}

	public void setUploadBankTime(java.lang.Integer uploadBankTime) {
		set("uploadBankTime", uploadBankTime);
	}
	
	public java.lang.Integer getUploadBankTime() {
		return getInt("uploadBankTime");
	}

	public void setUploadStatus(java.lang.Integer uploadStatus) {
		set("uploadStatus", uploadStatus);
	}
	
	public java.lang.Integer getUploadStatus() {
		return getInt("uploadStatus");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setBackup1(java.lang.Integer backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.Integer getBackup1() {
		return getInt("backup1");
	}

	public void setBackup2(java.lang.Integer backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.Integer getBackup2() {
		return getInt("backup2");
	}

	public void setBackup3(java.lang.Integer backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.Integer getBackup3() {
		return getInt("backup3");
	}

	public void setBackup4(java.lang.String backup4) {
		set("backup4", backup4);
	}
	
	public java.lang.String getBackup4() {
		return getStr("backup4");
	}

	public void setBackup5(java.lang.String backup5) {
		set("backup5", backup5);
	}
	
	public java.lang.String getBackup5() {
		return getStr("backup5");
	}

}
