package com.csnt.ins.model.issuer.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEtcIssuedRecord<M extends BaseEtcIssuedRecord<M>> extends Model<M> implements IBean {

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}
	
	public java.lang.String getUuid() {
		return getStr("uuid");
	}

	public void setVehicleId(java.lang.String vehicleId) {
		set("vehicleId", vehicleId);
	}
	
	public java.lang.String getVehicleId() {
		return getStr("vehicleId");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public void setBeforeObuId(java.lang.String beforeObuId) {
		set("beforeObuId", beforeObuId);
	}
	
	public java.lang.String getBeforeObuId() {
		return getStr("beforeObuId");
	}

	public void setBeforeObuStatus(java.lang.Integer beforeObuStatus) {
		set("beforeObuStatus", beforeObuStatus);
	}
	
	public java.lang.Integer getBeforeObuStatus() {
		return getInt("beforeObuStatus");
	}

	public void setObuId(java.lang.String obuId) {
		set("obuId", obuId);
	}

	public java.lang.String getObuId() {
		return getStr("obuId");
	}

	public void setObuStatus(java.lang.Integer obuStatus) {
		set("obuStatus", obuStatus);
	}

	public java.lang.Integer getObuStatus() {
		return getInt("obuStatus");
	}

	public void setBeforeCardId(java.lang.String beforeCardId) {
		set("beforeCardId", beforeCardId);
	}

	public java.lang.String getBeforeCardId() {
		return getStr("beforeCardId");
	}

	public void setBeforeCardStatus(java.lang.Integer beforeCardStatus) {
		set("beforeCardStatus", beforeCardStatus);
	}

	public java.lang.Integer getBeforeCardStatus() {
		return getInt("beforeCardStatus");
	}

	public void setCardId(java.lang.String cardId) {
		set("cardId", cardId);
	}
	
	public java.lang.String getCardId() {
		return getStr("cardId");
	}

	public void setCardStatus(java.lang.Integer cardStatus) {
		set("cardStatus", cardStatus);
	}
	
	public java.lang.Integer getCardStatus() {
		return getInt("cardStatus");
	}

	public void setBusinessType(java.lang.Integer businessType) {
		set("businessType", businessType);
	}
	
	public java.lang.Integer getBusinessType() {
		return getInt("businessType");
	}

	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}
	
	public java.lang.String getReason() {
		return getStr("reason");
	}

	public void setPosId(java.lang.String posId) {
		set("posId", posId);
	}
	
	public java.lang.String getPosId() {
		return getStr("posId");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}
	
	public java.lang.String getOperatorId() {
		return getStr("operatorId");
	}

	public void setOpTime(java.util.Date opTime) {
		set("opTime", opTime);
	}
	
	public java.util.Date getOpTime() {
		return get("opTime");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

	public void setBackup4(java.lang.String backup4) {
		set("backup4", backup4);
	}
	
	public java.lang.String getBackup4() {
		return getStr("backup4");
	}

	public void setBackup5(java.lang.String backup5) {
		set("backup5", backup5);
	}
	
	public java.lang.String getBackup5() {
		return getStr("backup5");
	}

}
