package com.csnt.ins.model.issuer.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePosUser<M extends BasePosUser<M>> extends Model<M> implements IBean {

	public void setUserName(java.lang.String userName) {
		set("USER_NAME", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("USER_NAME");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("USER_PWD", userPwd);
	}
	
	public java.lang.String getUserPwd() {
		return getStr("USER_PWD");
	}

	public void setPosId(String posId) {
		set("POS_ID", posId);
	}
	
	public String getPosId() {
		return getStr("POS_ID");
	}

	public void setPosName(String posName) {
		set("POS_NAME", posName);
	}

	public String getPosName() {
		return getStr("POS_NAME");
	}

	public void setPosName(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return getInt("type");
	}

	public void setChannelType(String channelType) {
		set("CHANNEL_TYPE", channelType);
	}

	public String getChannelType() {
		return getStr("CHANNEL_TYPE");
	}

	public void setIsActive(java.lang.Integer isActive) {
		set("IS_ACTIVE", isActive);
	}
	
	public java.lang.Integer getIsActive() {
		return getInt("IS_ACTIVE");
	}

	public void setUUID(java.lang.String UUID) {
		set("UUID", UUID);
	}
	
	public java.lang.String getUUID() {
		return getStr("UUID");
	}


	public void setUserId(java.lang.String UUID) {
		set("USER_ID", UUID);
	}

	public java.lang.String getUserId() {
		return getStr("USER_ID");
	}

	public void setUserCode(java.lang.String UUID) {
		set("ORG_CODE", UUID);
	}

	public java.lang.String getUserCode() {
		return getStr("ORG_CODE");
	}

	public void setLastModifyPasswordTime(Date lastModifyPasswordTime) {
		set("LAST_MODIFY_PASSWORD_TIME", lastModifyPasswordTime);
	}

	public Date getLastModifyPasswordTime() {
		return getDate("LAST_MODIFY_PASSWORD_TIME");
	}

}
