package com.csnt.ins.model.issuer.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEtcOflUserinfo<M extends BaseEtcOflUserinfo<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}
	
	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public void setAccessToken(java.lang.String accessToken) {
		set("accessToken", accessToken);
	}
	
	public java.lang.String getAccessToken() {
		return getStr("accessToken");
	}

	public void setExpiresIn(java.lang.Integer expiresIn) {
		set("expiresIn", expiresIn);
	}
	
	public java.lang.Integer getExpiresIn() {
		return getInt("expiresIn");
	}

	public void setDepUserId(java.lang.String depUserId) {
		set("depUserId", depUserId);
	}
	
	public java.lang.String getDepUserId() {
		return getStr("depUserId");
	}

	public void setUserIdNum(java.lang.String userIdNum) {
		set("userIdNum", userIdNum);
	}
	
	public java.lang.String getUserIdNum() {
		return getStr("userIdNum");
	}

	public void setUserIdType(java.lang.String userIdType) {
		set("userIdType", userIdType);
	}
	
	public java.lang.String getUserIdType() {
		return getStr("userIdType");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public void setPosId(java.lang.String posId) {
		set("posId", posId);
	}
	
	public java.lang.String getPosId() {
		return getStr("posId");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}
	
	public java.lang.String getOperatorId() {
		return getStr("operatorId");
	}

	public void setOpTime(java.util.Date opTime) {
		set("opTime", opTime);
	}
	
	public java.util.Date getOpTime() {
		return get("opTime");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

	public void setBackup4(java.lang.String backup4) {
		set("backup4", backup4);
	}
	
	public java.lang.String getBackup4() {
		return getStr("backup4");
	}

	public void setBackup5(java.lang.String backup5) {
		set("backup5", backup5);
	}
	
	public java.lang.String getBackup5() {
		return getStr("backup5");
	}

}
