package com.csnt.ins.model.issuer.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOnlineOrders<M extends BaseOnlineOrders<M>> extends Model<M> implements IBean {

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("orderId");
	}

	public void setOrderCreateTime(java.util.Date orderCreateTime) {
		set("orderCreateTime", orderCreateTime);
	}
	
	public java.util.Date getOrderCreateTime() {
		return get("orderCreateTime");
	}

	public void setVehicleId(java.lang.String vehicleId) {
		set("vehicleId", vehicleId);
	}
	
	public java.lang.String getVehicleId() {
		return getStr("vehicleId");
	}

	public void setVehicleCode(java.lang.String vehicleCode) {
		set("vehicleCode", vehicleCode);
	}
	
	public java.lang.String getVehicleCode() {
		return getStr("vehicleCode");
	}

	public void setAccountId(java.lang.String accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.String getAccountId() {
		return getStr("accountId");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public void setAccountName(java.lang.String accountName) {
		set("accountName", accountName);
	}
	
	public java.lang.String getAccountName() {
		return getStr("accountName");
	}

	public void setUserType(java.lang.Integer userType) {
		set("userType", userType);
	}
	
	public java.lang.Integer getUserType() {
		return getInt("userType");
	}

	public void setCardType(java.lang.Integer cardType) {
		set("cardType", cardType);
	}
	
	public java.lang.Integer getCardType() {
		return getInt("cardType");
	}

	public void setPayCardType(java.lang.Integer payCardType) {
		set("payCardType", payCardType);
	}
	
	public java.lang.Integer getPayCardType() {
		return getInt("payCardType");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setUserIdType(java.lang.Integer userIdType) {
		set("userIdType", userIdType);
	}
	
	public java.lang.Integer getUserIdType() {
		return getInt("userIdType");
	}

	public void setUserIdNum(java.lang.String userIdNum) {
		set("userIdNum", userIdNum);
	}
	
	public java.lang.String getUserIdNum() {
		return getStr("userIdNum");
	}

	public void setPostName(java.lang.String postName) {
		set("postName", postName);
	}
	
	public java.lang.String getPostName() {
		return getStr("postName");
	}

	public void setPostPhone(java.lang.String postPhone) {
		set("postPhone", postPhone);
	}
	
	public java.lang.String getPostPhone() {
		return getStr("postPhone");
	}

	public void setPostAddr(java.lang.String postAddr) {
		set("postAddr", postAddr);
	}
	
	public java.lang.String getPostAddr() {
		return getStr("postAddr");
	}

	public void setPlateNum(java.lang.String plateNum) {
		set("plateNum", plateNum);
	}
	
	public java.lang.String getPlateNum() {
		return getStr("plateNum");
	}

	public void setPlateColor(java.lang.Integer plateColor) {
		set("plateColor", plateColor);
	}
	
	public java.lang.Integer getPlateColor() {
		return getInt("plateColor");
	}

	public void setVehicleType(java.lang.Integer vehicleType) {
		set("vehicleType", vehicleType);
	}
	
	public java.lang.Integer getVehicleType() {
		return getInt("vehicleType");
	}

	public void setOutsideDimensions(java.lang.String outsideDimensions) {
		set("outsideDimensions", outsideDimensions);
	}
	
	public java.lang.String getOutsideDimensions() {
		return getStr("outsideDimensions");
	}

	public void setVin(java.lang.String vin) {
		set("vin", vin);
	}
	
	public java.lang.String getVin() {
		return getStr("vin");
	}

	public void setLimitPerNum(java.lang.Integer limitPerNum) {
		set("limitPerNum", limitPerNum);
	}
	
	public java.lang.Integer getLimitPerNum() {
		return getInt("limitPerNum");
	}

	public void setTotalWeight(java.lang.Integer totalWeight) {
		set("totalWeight", totalWeight);
	}
	
	public java.lang.Integer getTotalWeight() {
		return getInt("totalWeight");
	}

	public void setEngineNo(java.lang.String engineNo) {
		set("engineNo", engineNo);
	}
	
	public java.lang.String getEngineNo() {
		return getStr("engineNo");
	}

	public void setWheelCount(java.lang.Integer wheelCount) {
		set("wheelCount", wheelCount);
	}
	
	public java.lang.Integer getWheelCount() {
		return getInt("wheelCount");
	}

	public void setAxleCount(java.lang.Integer axleCount) {
		set("axleCount", axleCount);
	}
	
	public java.lang.Integer getAxleCount() {
		return getInt("axleCount");
	}

	public void setAxleDistance(java.lang.Integer axleDistance) {
		set("axleDistance", axleDistance);
	}
	
	public java.lang.Integer getAxleDistance() {
		return getInt("axleDistance");
	}

	public void setAxisType(java.lang.String axisType) {
		set("axisType", axisType);
	}
	
	public java.lang.String getAxisType() {
		return getStr("axisType");
	}

	public void setDelivery(java.lang.Integer delivery) {
		set("delivery", delivery);
	}
	
	public java.lang.Integer getDelivery() {
		return getInt("delivery");
	}

	public void setExpressType(java.lang.Integer expressType) {
		set("expressType", expressType);
	}
	
	public java.lang.Integer getExpressType() {
		return getInt("expressType");
	}

	public void setExpressId(java.lang.String expressId) {
		set("expressId", expressId);
	}
	
	public java.lang.String getExpressId() {
		return getStr("expressId");
	}

	public void setObuId(java.lang.String obuId) {
		set("obuId", obuId);
	}
	
	public java.lang.String getObuId() {
		return getStr("obuId");
	}

	public void setCardId(java.lang.String cardId) {
		set("cardId", cardId);
	}
	
	public java.lang.String getCardId() {
		return getStr("cardId");
	}

	public void setChannelType(java.lang.String channelType) {
		set("channelType", channelType);
	}
	
	public java.lang.String getChannelType() {
		return getStr("channelType");
	}

	public void setBankCode(java.lang.String bankCode) {
		set("bankCode", bankCode);
	}
	
	public java.lang.String getBankCode() {
		return getStr("bankCode");
	}

	public void setPosId(java.lang.String posId) {
		set("posId", posId);
	}
	
	public java.lang.String getPosId() {
		return getStr("posId");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}
	
	public java.lang.String getOperatorId() {
		return getStr("operatorId");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setPostStatus(java.lang.Integer postStatus) {
		set("postStatus", postStatus);
	}
	
	public java.lang.Integer getPostStatus() {
		return getInt("postStatus");
	}

	public void setSyncStatus(java.lang.Integer syncStatus) {
		set("syncStatus", syncStatus);
	}
	
	public java.lang.Integer getSyncStatus() {
		return getInt("syncStatus");
	}

	public void setSyncTime(java.util.Date syncTime) {
		set("syncTime", syncTime);
	}
	
	public java.util.Date getSyncTime() {
		return get("syncTime");
	}

	public void setSyncPostStatus(java.lang.Integer syncPostStatus) {
		set("syncPostStatus", syncPostStatus);
	}
	
	public java.lang.Integer getSyncPostStatus() {
		return getInt("syncPostStatus");
	}

	public void setSyncPostTime(java.util.Date syncPostTime) {
		set("syncPostTime", syncPostTime);
	}
	
	public java.util.Date getSyncPostTime() {
		return get("syncPostTime");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

	public void setBackup4(java.lang.String backup4) {
		set("backup4", backup4);
	}
	
	public java.lang.String getBackup4() {
		return getStr("backup4");
	}

	public void setBackup5(java.lang.String backup5) {
		set("backup5", backup5);
	}
	
	public java.lang.String getBackup5() {
		return getStr("backup5");
	}

	public void setOrderType(java.lang.Integer orderType) {
		set("orderType", orderType);
	}
	
	public java.lang.Integer getOrderType() {
		return getInt("orderType");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channelId", channelId);
	}

	public java.lang.String getChannelId() {
		return getStr("channelId");
	}

	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("orderStatus", orderStatus);
	}

	public java.lang.Integer getOrderStatus() {
		return getInt("orderStatus");
	}
}
