package com.csnt.ins.model.issuer.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePosLoginLog<M extends BasePosLoginLog<M>> extends Model<M> implements IBean {

    public void setUUID(java.lang.String UUID) {
        set("UUID", UUID);
    }

    public java.lang.String getUUID() {
        return getStr("UUID");
    }

    public void setUserId(java.lang.String userId) {
        set("USER_ID", userId);
    }

    public java.lang.String getUserId() {
        return getStr("USER_ID");
    }

    public void setPosId(String posId) {
        set("POS_ID", posId);
    }

    public Integer getPosId() {
        return getInt("POS_ID");
    }

    public void setLoginTime(java.util.Date loginTime) {
        set("LOGIN_TIME", loginTime);
    }

    public java.util.Date getLoginTime() {
        return get("LOGIN_TIME");
    }

    public void setHOST(java.lang.String HOST) {
        set("HOST", HOST);
    }

    public java.lang.String getHOST() {
        return getStr("HOST");
    }

    public void setLoginStatus(java.lang.Integer loginStatus) {
        set("LOGIN_STATUS", loginStatus);
    }

    public java.lang.Integer getLoginStatus() {
        return getInt("LOGIN_STATUS");
    }

    public void setLoginMsg(java.lang.String loginMsg) {
        set("LOGIN_MSG", loginMsg);
    }

    public java.lang.String getLoginMsg() {
        return getStr("LOGIN_MSG");
    }

    public void setLongitude(java.lang.Double longitude) {
        set("LONGITUDE", longitude);
    }

    public java.lang.Double getLongitude() {
        return getDouble("LONGITUDE");
    }

    public void setLatitude(java.lang.Double latitude) {
        set("LATITUDE", latitude);
    }

    public java.lang.Double getLatitude() {
        return getDouble("LATITUDE");
    }

}
