package com.csnt.ins.model.issuer.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEtcUserinfoHistory<M extends BaseEtcUserinfoHistory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUserType(java.lang.Integer userType) {
		set("userType", userType);
	}
	
	public java.lang.Integer getUserType() {
		return getInt("userType");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public void setUserIdType(java.lang.Integer userIdType) {
		set("userIdType", userIdType);
	}
	
	public java.lang.Integer getUserIdType() {
		return getInt("userIdType");
	}

	public void setUserIdNum(java.lang.String userIdNum) {
		set("userIdNum", userIdNum);
	}
	
	public java.lang.String getUserIdNum() {
		return getStr("userIdNum");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setRegisteredType(java.lang.Integer registeredType) {
		set("registeredType", registeredType);
	}
	
	public java.lang.Integer getRegisteredType() {
		return getInt("registeredType");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channelId", channelId);
	}
	
	public java.lang.String getChannelId() {
		return getStr("channelId");
	}

	public void setRegisteredTime(java.util.Date registeredTime) {
		set("registeredTime", registeredTime);
	}
	
	public java.util.Date getRegisteredTime() {
		return get("registeredTime");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}
	
	public java.lang.String getDepartment() {
		return getStr("department");
	}

	public void setAgentName(java.lang.String agentName) {
		set("agentName", agentName);
	}
	
	public java.lang.String getAgentName() {
		return getStr("agentName");
	}

	public void setAgentIdType(java.lang.Integer agentIdType) {
		set("agentIdType", agentIdType);
	}
	
	public java.lang.Integer getAgentIdType() {
		return getInt("agentIdType");
	}

	public void setAgentIdNum(java.lang.String agentIdNum) {
		set("agentIdNum", agentIdNum);
	}
	
	public java.lang.String getAgentIdNum() {
		return getStr("agentIdNum");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}
	
	public java.lang.String getBank() {
		return getStr("bank");
	}

	public void setBankAddr(java.lang.String bankAddr) {
		set("bankAddr", bankAddr);
	}
	
	public java.lang.String getBankAddr() {
		return getStr("bankAddr");
	}

	public void setBankAccount(java.lang.String bankAccount) {
		set("bankAccount", bankAccount);
	}
	
	public java.lang.String getBankAccount() {
		return getStr("bankAccount");
	}

	public void setTaxpayerCode(java.lang.String taxpayerCode) {
		set("taxpayerCode", taxpayerCode);
	}
	
	public java.lang.String getTaxpayerCode() {
		return getStr("taxpayerCode");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setStatusChangeTime(java.util.Date statusChangeTime) {
		set("statusChangeTime", statusChangeTime);
	}
	
	public java.util.Date getStatusChangeTime() {
		return get("statusChangeTime");
	}

	public void setFaceFeatureVersion(java.lang.String faceFeatureVersion) {
		set("faceFeatureVersion", faceFeatureVersion);
	}
	
	public java.lang.String getFaceFeatureVersion() {
		return getStr("faceFeatureVersion");
	}

	public void setFaceFeatureCode(java.lang.String faceFeatureCode) {
		set("faceFeatureCode", faceFeatureCode);
	}
	
	public java.lang.String getFaceFeatureCode() {
		return getStr("faceFeatureCode");
	}

	public void setOperation(java.lang.Integer operation) {
		set("operation", operation);
	}
	
	public java.lang.Integer getOperation() {
		return getInt("operation");
	}

	public void setChannelType(java.lang.String channelType) {
		set("channelType", channelType);
	}
	
	public java.lang.String getChannelType() {
		return getStr("channelType");
	}

	public void setNeedupload(java.lang.Integer needupload) {
		set("needupload", needupload);
	}
	
	public java.lang.Integer getNeedupload() {
		return getInt("needupload");
	}

	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}
	
	public java.lang.String getOrgId() {
		return getStr("orgId");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}
	
	public java.lang.String getOperatorId() {
		return getStr("operatorId");
	}

	public void setOpTime(java.util.Date opTime) {
		set("opTime", opTime);
	}
	
	public java.util.Date getOpTime() {
		return get("opTime");
	}

	public void setUploadResult(java.lang.String uploadResult) {
		set("uploadResult", uploadResult);
	}
	
	public java.lang.String getUploadResult() {
		return getStr("uploadResult");
	}

	public void setUploadResultMsg(java.lang.String uploadResultMsg) {
		set("uploadResultMsg", uploadResultMsg);
	}
	
	public java.lang.String getUploadResultMsg() {
		return getStr("uploadResultMsg");
	}

	public void setUploadTime(java.util.Date uploadTime) {
		set("uploadTime", uploadTime);
	}
	
	public java.util.Date getUploadTime() {
		return get("uploadTime");
	}

	public void setResponseTime(java.util.Date responseTime) {
		set("responseTime", responseTime);
	}
	
	public java.util.Date getResponseTime() {
		return get("responseTime");
	}

	public void setIsuploadBank(java.lang.Integer isuploadBank) {
		set("isuploadBank", isuploadBank);
	}
	
	public java.lang.Integer getIsuploadBank() {
		return getInt("isuploadBank");
	}

	public void setUploadBankResult(java.lang.String uploadBankResult) {
		set("uploadBankResult", uploadBankResult);
	}
	
	public java.lang.String getUploadBankResult() {
		return getStr("uploadBankResult");
	}

	public void setUploadBankResultMsg(java.lang.String uploadBankResultMsg) {
		set("uploadBankResultMsg", uploadBankResultMsg);
	}
	
	public java.lang.String getUploadBankResultMsg() {
		return getStr("uploadBankResultMsg");
	}

	public void setUploadBankTime(java.util.Date uploadBankTime) {
		set("uploadBankTime", uploadBankTime);
	}
	
	public java.util.Date getUploadBankTime() {
		return get("uploadBankTime");
	}

	public void setUploadStatus(java.lang.Integer uploadStatus) {
		set("uploadStatus", uploadStatus);
	}
	
	public java.lang.Integer getUploadStatus() {
		return getInt("uploadStatus");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setBackup1(java.lang.Integer backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.Integer getBackup1() {
		return getInt("backup1");
	}

	public void setBackup2(java.lang.Integer backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.Integer getBackup2() {
		return getInt("backup2");
	}

	public void setBackup3(java.lang.Integer backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.Integer getBackup3() {
		return getInt("backup3");
	}

	public void setBackup4(java.lang.String backup4) {
		set("backup4", backup4);
	}
	
	public java.lang.String getBackup4() {
		return getStr("backup4");
	}

	public void setBackup5(java.lang.String backup5) {
		set("backup5", backup5);
	}
	
	public java.lang.String getBackup5() {
		return getStr("backup5");
	}

}
