package com.csnt.ins.model.yg;

import com.csnt.ins.model.yg.base.BaseTblObu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblObu extends BaseTblObu<TblObu> {
	public static final TblObu dao = new TblObu().dao();
}
