package com.csnt.ins.model.yg;

import com.csnt.ins.model.yg.base.BaseTblUsercard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblUsercard extends BaseTblUsercard<TblUsercard> {
	public static final TblUsercard dao = new TblUsercard().dao();
}
