package com.csnt.ins.model.yg;

import com.csnt.ins.model.yg.base.BaseTblVehicle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblVehicle extends BaseTblVehicle<TblVehicle> {
	public static final TblVehicle dao = new TblVehicle().dao();
}
